FROM node:18-alpine as builder



WORKDIR /app

COPY . .

RUN npm i -g pnpm

RUN pnpm install 

RUN pnpm run build

FROM nginx:1.21-alpine

COPY --from=builder /app/dist /usr/share/nginx/html


EXPOSE 80

CMD ["nginx","-g","daemon off;"]
