FROM golang:1.20-alpine AS builder

WORKDIR /app

COPY . .
RUN go mod tidy -e
RUN go get -t
RUN go build -o backend

FROM golang:1.20-alpine

WORKDIR /app

COPY --from=builder /app/backend .

EXPOSE 1100

CMD ["./backend"]
